version: "3.9"

services:
  users-service:
    container_name: users-service
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env.production.local
    networks:
      - qb1tycinema

networks:
  qb1tycinema:
    external: true